# Generated by Django 4.2.3 on 2023-10-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_members"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="")),
                ("name", models.TextField()),
                ("post", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="Members",
        ),
    ]
